generators-gui:
  enabled: true

  title: "Generators"
  rows: 5

  default-lore:
    - "&7Tier: &a%tier%"
    - "&7Speed: &a%speed%"
    - "&7Spawn Item: &a%spawnItem%"
    - "&7Block Type: &a%blockType%"
    - "&7Status: &a%status%"

generators:
  - name: "generator1"
    tier: 1
    price: 1000.0
    speed: 10
    spawnItem: "DIAMOND"
    blockType: "DIAMOND_BLOCK"
  - name: "generator2"
    tier: 2
    price: 1000.0
    speed: 10
    spawnItem: "STONE"
    blockType: "STONE"