# Specify the time after which the item will despawn from the time it was spawned.
# The despawn time can be specified in the following format variations:
# - "1h" for 1 hour
# - "5m" for 5 minutes
# - "1h 5m" for 1 hour and 5 minutes
# - "1h 5m 5s" for 1 hour and 5 minutes 5 seconds
item-despawn-time: "5m"

# If set to false, players will not be able to place generator drops.
# If player places generator drop, it will lose all it
# values and will be turned into a normal block.
can-drops-be-placed: false

limit-settings:
  # If enabled is set to false, the limit will not be checked.
  enabled: true

  # What should be the limit of generators per player.
  limit: 10

guis:
  # Gui to view generators by a command
  generators-gui:
    # If enabled is set to false, the command will not be registered.
    enabled: true

    # Title of the gui
    title: "Generators"

    # Number of rows in the gui
    rows: 5

  # Gui when upgrading generator
  upgrade-gui:
    upgradeOne:
      first-line: "&e》 &nClick to upgrade generator!&e 《"
      # If lore is not specified, the default lore will be used.
      # The default lore can be specified in the following format:
      # - %tier%" equals to the generator's tier
      # - %speed%" is the generator's speed of spawning items
      # - %price%" is the price of generator
      # - %sellPrice%" is the sell price of generator drop
      # - %spawnItem%" equals to what item will generator spawn
      # - %blockType%" equals to block type of generator
      # - %nextTier% equals to the next tier of generator
      # - %nextSpeed% equals to the next speed of generator
      # - %nextPrice% equals to the next price of generator
      # - %nextSellPrice% equals to the next sell price of generator
      # - %nextSpawnItem% equals to the next spawn item of generator
      # - %nextBlockType% equals to the next block type of generator
      lore:
        - "&fMoney: &a%money%"
        - "&fUpgrade Price: &a%upgradePrice%"
        - ""
        - "&aUpgrade Details:"
        - "&b%tier% &r&8》&d&l%nextTier% &0&lASD"
        - "&b%speed%s &8》&d&l%nextSpeed%s"
        - "&b%price% &r&8》&d&l%nextPrice%"
        - "&b%sellPrice% &r&8》&d&l%nextSellPrice%"
        - "&b%spawnItem% &r&8》&d&l%nextSpawnItem%"
        - "&b%blockType% &r&8》&d&l%nextBlockType%"
        - "&8&l&n                                "

    upgradeAll:
        first-line: "&e》 &nClick to upgrade all generators!&e 《"
        # If lore is not specified, the default lore will be used.
        # The default lore can be specified in the following format:
        # - %tier%" equals to the generator's tier
        # - %speed%" is the generator's speed of spawning items
        # - %price%" is the price of generator
        # - %sellPrice%" is the sell price of generator drop
        # - %spawnItem%" equals to what item will generator spawn
        # - %blockType%" equals to block type of generator
        # - %nextTier% equals to the next tier of generator
        # - %nextSpeed% equals to the next speed of generator
        # - %nextPrice% equals to the next price of generator
        # - %nextSellPrice% equals to the next sell price of generator
        # - %nextSpawnItem% equals to the next spawn item of generator
        # - %nextBlockType% equals to the next block type of generator
        lore:
            - "&fMoney: &a%money%"
            - "&fUpgrade Price: &a%upgradePrice%"
            - ""
            - "&aUpgrade Details:"
            - "&b%tier% &r&8》&d&l%nextTier% &0&lASD"
            - "&b%speed%s &8》&d&l%nextSpeed%s"
            - "&b%price% &r&8》&d&l%nextPrice%"
            - "&b%sellPrice% &r&8》&d&l%nextSellPrice%"
            - "&b%spawnItem% &r&8》&d&l%nextSpawnItem%"
            - "&b%blockType% &r&8》&d&l%nextBlockType%"
            - "&8&l&n                                "

    # Title of the gui
    title: "Upgrade Generator"

    # Number of rows in the gui
    rows: 3

holograms:
  view-distance: 300

events:
  # time can be specified in the following format variations:
  # - "1h" for 1 hour
  # - "5m" for 5 minutes
  # - "1h 5m" for 1 hour and 5 minutes
  # - "1h 5m 5s" for 1 hour and 5 minutes and 5 seconds

  # Time duration between events
  time-between-events: "1h"

  # Duration of each event
  event-duration: "2m"

  broadcast:
    # If enabled is set to false, there will be no broadcast messages.
    enabled: true

  drop-event:
    # If enabled is set to false, the event will not be registered.
    enabled: true

    # Name of the drop event
    name: "Drop Event"

    # Multiplier for the event
    multiplier: 2

  sell-event:
    # If enabled is set to false, the event will not be registered.
    enabled: true

    # Name of the sell event
    name: "Sell Event"

    # Multiplier for the event
    multiplier: 2

  speed-event:
    # If enabled is set to false, the event will not be registered.
    enabled: true

    # Name of the speed event
    name: "Speed Event"

    # Multiplier for the event
    multiplier: 2

particles:
  # If enabled is set to false, particles will not be displayed upon upgrade.
  enabled: true

  # Type of the particle. Make sure to use particles
  # that are supported by your server version, otherwise,
  # the particles will not be displayed. You can find
  # all supported particles here:
  # https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Particle.html
  type: "FIREWORKS_SPARK"

  # Sound that will be played upon upgrade.
  # You can find all supported sounds here:
  # https://github.com/dieterblancke/DonatorJoinPlus/blob/master/spigot/src/main/java/com/dbsoftwares/djp/spigot/utils/XSound.java
  sound: "ENTITY_FIREWORK_ROCKET_BLAST"

# If lore is not specified, the default lore will be used.
# The default lore can be specified in the following format:
# - %tier%" equals to the generator's tier
# - %speed%" is the generator's speed of spawning items
# - %price%" is the price of generator
# - %sellPrice%" is the sell price of generator drop
# - %spawnItem%" equals to what item will generator spawn
# - %blockType%" equals to block type of generator
default-lore:
  - "&7Tier: &a%tier%"
  - "&7Speed: &a%speed%"
  - "&7Price: &a%price%"
  - "&7Sell Price: &a%sellPrice%"
  - "&7Spawn Item: &a%spawnItem%"
  - "&7Block Type: &a%blockType%"

# If itemSpawnLore is not specified, the default item spawn lore will be used.
# The default item spawn lore can be specified in the following format:
# - %sellPrice%" is the sell price of the generator drop
default-item-spawn-lore:
  - "&7Type in chat &a/selldrops &7to sell drops!"
  - "&7Drops are selling for &a%sellPrice%&7!"

# If hologramLines is not specified, the default hologram lines will be used.
# The default hologram lines can be specified in the following format:
# Lines that will be displayed above the generator
# Lines can be specified in the following format:
# %name% will be replaced with the name of the generator
# %tier% will be replaced with the tier of the generator
# %speed% will be replaced with the speed of the generator
# %spawnItem% will be replaced with the item that generator spawns
# %sellPrice% will be replaced with the sell price of the generator
default-hologram-lines:
  - "&a%name%"
  - "&7Tier: &a%tier%"
  - "&7Spawns each &a%speed% &7seconds &a%spawnItem%"
  - "&7Sells for &a%sellPrice%"

# generators represent the generators that will be added in the gui,
# name is the name of the generator
# tier is the tier of the generator (each generator must have a unique tier)
# price is the price of the generator
# sellPrice is the sell price of the generator drop
# speed is the speed of the generator (how often it will spawn items)
# spawnItem is the item that generator will spawn
# blockType is the block type of the generator
# lore is the lore of the generator (if not specified, the default lore will be used)
generators:
  - name: "&7&lStone Generator"
    tier: 1
    price: 50.0
    sellPrice: 10.0
    speed: 20
    spawnItem: "STONE"
    blockType: "STONE"
    lore: []
    itemSpawnLore: []
    hologramLines: []
    dropDisplayName: "&7&lStone Drop"
  - name: "&e&lSandstone Generator"
    tier: 2
    price: 100.0
    sellPrice: 20.0
    speed: 20
    spawnItem: "SANDSTONE"
    blockType: "SANDSTONE"
    lore: []
    itemSpawnLore: []
    hologramLines: []
    dropDisplayName: "&e&lSandstone Drop"
  - name: "&f&lChiseled Sandstone Generator"
    tier: 3
    price: 200.0
    sellPrice: 25.0
    speed: 20
    spawnItem: "CHISELED_SANDSTONE"
    blockType: "CHISELED_SANDSTONE"
    lore: []
    itemSpawnLore: []
    hologramLines: []
    dropDisplayName: "&f&lChiseled Sandstone Drop"
  - name: "&6&lRed Sandstone Generator"
    tier: 4
    price: 300.0
    sellPrice: 50.0
    speed: 20
    spawnItem: "RED_SANDSTONE"
    blockType: "RED_SANDSTONE"
    lore: []
    itemSpawnLore: []
    hologramLines: []
    dropDisplayName: "&6&lRed Sandstone Drop"
  - name: "&8&lCoal Generator"
    tier: 5
    price: 400.0
    sellPrice: 75.0
    speed: 20
    spawnItem: "COAL"
    blockType: "COAL_ORE"
    lore: []
    itemSpawnLore: []
    hologramLines: []
    dropDisplayName: "&8&lCoal Drop"
  - name: "&7&lIron Generator"
    tier: 6
    price: 500.0
    sellPrice: 100.0
    speed: 20
    spawnItem: "IRON_INGOT"
    blockType: "IRON_ORE"
    lore: []
    itemSpawnLore: []
    hologramLines: []
    dropDisplayName: "&7&lIron Drop"
  - name: "&6&lGold Generator"
    tier: 7
    price: 750.0
    sellPrice: 150.0
    speed: 20
    spawnItem: "GOLD_INGOT"
    blockType: "GOLD_ORE"
    lore: []
    itemSpawnLore: []
    hologramLines: []
    dropDisplayName: "&6&lGold Drop"
  - name: "&b&lDiamond Generator"
    tier: 8
    price: 1000.0
    sellPrice: 200.0
    speed: 20
    spawnItem: "DIAMOND"
    blockType: "DIAMOND_ORE"
    lore: []
    itemSpawnLore: []
    hologramLines: []
    dropDisplayName: "&b&lDiamond Drop"
  - name: "&5&lObsidian Generator"
    tier: 9
    price: 5000.0
    sellPrice: 300.0
    speed: 20
    spawnItem: "OBSIDIAN"
    blockType: "OBSIDIAN"
    lore: []
    itemSpawnLore: []
    hologramLines: []
    dropDisplayName: "&5&lObsidian Drop"
  - name: "&4&lBedrock Generator"
    tier: 10
    price: 10000.0
    sellPrice: 400.0
    speed: 20
    spawnItem: "BEDROCK"
    blockType: "BEDROCK"
    lore: []
    itemSpawnLore: []
    hologramLines: []
    dropDisplayName: "&4&lBedrock Drop"

developer-options:
  debug: false