# Specify the time after which the item will despawn from the time it was spawned.
# The despawn time can be specified in the following format variations:
# - "1h" for 1 hour
# - "5m" for 5 minutes
# - "1h 5m" for 1 hour and 5 minutes
# - "1h 5m 5s" for 1 hour and 5 minutes 5 seconds
item-despawn-time: "5m"

limit-settings:
  enabled: true

  limit: 10

  message: "&cYou have reached the limit of %limit% generators!"

guis:
  # Gui to view generators by a command
  generators-gui:
    # If enabled is set to false, the command will not be registered.
    enabled: true

    # Title of the gui
    title: "Generators"

    # Number of rows in the gui
    rows: 5

  # Gui when upgrading generator
  upgrade-gui:
    first-line: "&e》 &nClick to upgrade generator!&e 《"
    # If lore is not specified, the default lore will be used.
    # The default lore can be specified in the following format:
    # - %tier%" equals to the generator's tier
    # - %speed%" is the generator's speed of spawning items
    # - %price%" is the price of generator
    # - %sellPrice%" is the sell price of generator drop
    # - %spawnItem%" equals to what item will generator spawn
    # - %blockType%" equals to block type of generator
    # - %nextTier% equals to the next tier of generator
    # - %nextSpeed% equals to the next speed of generator
    # - %nextPrice% equals to the next price of generator
    # - %nextSellPrice% equals to the next sell price of generator
    # - %nextSpawnItem% equals to the next spawn item of generator
    # - %nextBlockType% equals to the next block type of generator
    lore:
      - "&fMoney: &a%money%"
      - "&fUpgrade Price: &a%upgradePrice%"
      - ""
      - "&aUpgrade Details:"
      - "&b%tier% &r&8》&d&l%nextTier% &0&lASD"
      - "&b%speed%s &8》&d&l%nextSpeed%s"
      - "&b%price% &r&8》&d&l%nextPrice%"
      - "&b%sellPrice% &r&8》&d&l%nextSellPrice%"
      - "&b%spawnItem% &r&8》&d&l%nextSpawnItem%"
      - "&b%blockType% &r&8》&d&l%nextBlockType%"
      - "&8&l&n                                "


    # Title of the gui
    title: "Upgrade Generator"

    # Number of rows in the gui
    rows: 3

holograms:
  view-distance: 300

  # Lines that will be displayed above the generator
  # Lines can be specified in the following format:
  # %name% will be replaced with the name of the generator
  # %tier% will be replaced with the tier of the generator
  # %speed% will be replaced with the speed of the generator
  # %spawnItem% will be replaced with the item that generator spawns
  # %sellPrice% will be replaced with the sell price of the generator
  lines:
    - "&a%name%"
    - "&7Tier: &a%tier%"
    - "&7Spawns each &a%speed% &7seconds &a%spawnItem%"
    - "&7Sells for &a%sellPrice%"

events:
  # time can be specified in the following format variations:
  # - "1h" for 1 hour
  # - "5m" for 5 minutes
  # - "1h 5m" for 1 hour and 5 minutes
  # - "1h 5m 5s" for 1 hour and 5 minutes and 5 seconds

  # Time duration between events
  time-between-events: "1h"

  # Duration of each event
  event-duration: "2m"

  broadcast:
    # If enabled is set to false, there will be no broadcast messages.
    enabled: true

    # Message when event starts
    # %event% will be replaced with the name of the event
    event-started: "&a&lEVENT> &7%event% has started and will end in &e&n%time%!"

    # Message when event ends
    # %event% will be replaced with the name of the event
    event-ended: "&a&lEVENT> &7%event% has ended and new event will be started in &e&n%time%!"

  drop-event:
    # If enabled is set to false, the event will not be registered.
    enabled: true

    # Name of the drop event
    name: "Drop Event"

    # Multiplier for the event
    multiplier: 2

  sell-event:
    # If enabled is set to false, the event will not be registered.
    enabled: true

    # Name of the sell event
    name: "Sell Event"

    # Multiplier for the event
    multiplier: 2

  speed-event:
    # If enabled is set to false, the event will not be registered.
    enabled: true

    # Name of the speed event
    name: "Speed Event"

    # Multiplier for the event
    multiplier: 2

# If lore is not specified, the default lore will be used.
# The default lore can be specified in the following format:
# - %tier%" equals to the generator's tier
# - %speed%" is the generator's speed of spawning items
# - %price%" is the price of generator
# - %sellPrice%" is the sell price of generator drop
# - %spawnItem%" equals to what item will generator spawn
# - %blockType%" equals to block type of generator
default-lore:
  - "&7Tier: &a%tier%"
  - "&7Speed: &a%speed%"
  - "&7Price: &a%price%"
  - "&7Sell Price: &a%sellPrice%"
  - "&7Spawn Item: &a%spawnItem%"
  - "&7Block Type: &a%blockType%"

# If itemSpawnLore is not specified, the default item spawn lore will be used.
# The default item spawn lore can be specified in the following format:
# - %sellPrice%" is the sell price of the generator drop
default-item-spawn-lore:
  - "&7Type in chat &a/selldrops &7to sell drops!"
  - "&7Drops are selling for &a%sellPrice%&7!"

# generators represent the generators that will be added in the gui,
# name is the name of the generator
# tier is the tier of the generator (each generator must have a unique tier)
# price is the price of the generator
# sellPrice is the sell price of the generator drop
# speed is the speed of the generator (how often it will spawn items)
# spawnItem is the item that generator will spawn
# blockType is the block type of the generator
# lore is the lore of the generator (if not specified, the default lore will be used)
generators:
  - name: "&e&lWheat Generator"
    tier: 1
    price: 50.0
    sellPrice: 10.0
    speed: 20
    spawnItem: "WHEAT"
    blockType: "HAY_BLOCK"
    lore: []
    itemSpawnLore: []
  - name: "&a&lMelon Generator"
    tier: 2
    price: 100.0
    sellPrice: 20.0
    speed: 20
    spawnItem: "MELON_SLICE"
    blockType: "MELON"
    lore: []
    itemSpawnLore: []
  - name: "&8&lCoal Generator"
    tier: 3
    price: 200.0
    sellPrice: 25.0
    speed: 20
    spawnItem: "COAL"
    blockType: "COAL_ORE"
    lore: []
    itemSpawnLore: []
  - name: "&8&lCoal Block Generator"
    tier: 4
    price: 300.0
    sellPrice: 50.0
    speed: 20
    spawnItem: "COAL_BLOCK"
    blockType: "COAL_BLOCK"
    lore: []
    itemSpawnLore: []
  - name: "&7&lIron Generator"
    tier: 5
    price: 400.0
    sellPrice: 75.0
    speed: 20
    spawnItem: "IRON_INGOT"
    blockType: "IRON_ORE"
    lore: []
    itemSpawnLore: []
  - name: "&7&lIron Block Generator"
    tier: 6
    price: 500.0
    sellPrice: 100.0
    speed: 20
    spawnItem: "IRON_BLOCK"
    blockType: "IRON_BLOCK"
    lore: []
    itemSpawnLore: []
  - name: "&6&lGold Generator"
    tier: 7
    price: 750.0
    sellPrice: 150.0
    speed: 20
    spawnItem: "GOLD_INGOT"
    blockType: "GOLD_ORE"
    lore: []
    itemSpawnLore: []
  - name: "&6&lGold Block Generator"
    tier: 8
    price: 1000.0
    sellPrice: 200.0
    speed: 20
    spawnItem: "GOLD_BLOCK"
    blockType: "GOLD_BLOCK"
    lore: []
    itemSpawnLore: []
  - name: "&4&lRedstone Generator"
    tier: 9
    price: 5000.0
    sellPrice: 300.0
    speed: 20
    spawnItem: "REDSTONE"
    blockType: "REDSTONE_ORE"
    lore: []
    itemSpawnLore: []
  - name: "&4&lRedstone Block Generator"
    tier: 10
    price: 10000.0
    sellPrice: 400.0
    speed: 20
    spawnItem: "REDSTONE_BLOCK"
    blockType: "REDSTONE_BLOCK"
    lore: []
    itemSpawnLore: []
  - name: "&b&lLapis Generator"
    tier: 11
    price: 25000.0
    sellPrice: 500.0
    speed: 20
    spawnItem: "LAPIS_LAZULI"
    blockType: "LAPIS_ORE"
    lore: []
    itemSpawnLore: []
  - name: "&b&lLapis Block Generator"
    tier: 12
    price: 50000.0
    sellPrice: 600.0
    speed: 20
    spawnItem: "LAPIS_BLOCK"
    blockType: "LAPIS_BLOCK"
    lore: []
    itemSpawnLore: []
  - name: "&3&lDiamond Generator"
    tier: 13
    price: 100000.0
    sellPrice: 700.0
    speed: 20
    spawnItem: "DIAMOND"
    blockType: "DIAMOND_ORE"
    lore: []
    itemSpawnLore: []
  - name: "&3&lDiamond Block Generator"
    tier: 14
    price: 250000.0
    sellPrice: 800.0
    speed: 20
    spawnItem: "DIAMOND_BLOCK"
    blockType: "DIAMOND_BLOCK"
    lore: []
    itemSpawnLore: []
  - name: "&a&lEmerald Generator"
    tier: 15
    price: 500000.0
    sellPrice: 900.0
    speed: 20
    spawnItem: "EMERALD"
    blockType: "EMERALD_ORE"
    lore: []
    itemSpawnLore: []
  - name: "&a&lEmerald Block Generator"
    tier: 16
    price: 1000000.0
    sellPrice: 1000.0
    speed: 20
    spawnItem: "EMERALD_BLOCK"
    blockType: "EMERALD_BLOCK"
    lore: []
    itemSpawnLore: []
  - name: "&e&lNetherrack Generator"
    tier: 17
    price: 2500000.0
    sellPrice: 2000.0
    speed: 20
    spawnItem: "NETHERRACK"
    blockType: "NETHERRACK"
    lore: []
    itemSpawnLore: []
  - name: "&f&lQuartz Generator"
    tier: 18
    price: 5000000.0
    sellPrice: 2500.0
    speed: 20
    spawnItem: "QUARTZ"
    blockType: "NETHER_QUARTZ_ORE"
    lore: []
    itemSpawnLore: []
  - name: "&f&lNether Gold Generator"
    tier: 19
    price: 10000000.0
    sellPrice: 3000.0
    speed: 20
    spawnItem: "GOLD_NUGGET"
    blockType: "NETHER_GOLD_ORE"
    lore: []
    itemSpawnLore: []
  - name: "&e&lNether Brick Generator"
    tier: 20
    price: 25000000.0
    sellPrice: 3500.0
    speed: 20
    spawnItem: "NETHER_BRICK"
    blockType: "NETHER_BRICKS"
    lore: []
    itemSpawnLore: []
  - name: "&c&lNether Wart Generator"
    tier: 21
    price: 50000000.0
    sellPrice: 4000.0
    speed: 20
    spawnItem: "NETHER_WART"
    blockType: "NETHER_WART_BLOCK"
    lore: []
    itemSpawnLore: []
  - name: "&c&lObsidian Generator"
    tier: 22
    price: 100000000.0
    sellPrice: 4500.0
    speed: 20
    spawnItem: "OBSIDIAN"
    blockType: "OBSIDIAN"
    lore: []
    itemSpawnLore: []
  - name: "&c&lCrying Obsidian Generator"
    tier: 23
    price: 150000000.0
    sellPrice: 5000.0
    speed: 20
    spawnItem: "CRYING_OBSIDIAN"
    blockType: "CRYING_OBSIDIAN"
    lore: []
    itemSpawnLore: []
  - name: "&c&lObsidian Rose Generator"
    tier: 24
    price: 200000000.0
    sellPrice: 5500.0
    speed: 20
    spawnItem: "WITHER_ROSE"
    blockType: "RESPAWN_ANCHOR"
    lore: []
    itemSpawnLore: []

developer-options:
  debug: false