name: InfiniteForge
version: '${project.version}'
main: xyz.arcadiadevs.infiniteforge.InfiniteForge
api-version: 1.19
authors:
  - Cuftica
  - OpenSource

depend:
  - Vault

commands:
  getitem:
    description: Get the generator item
    usage: /getitem
    permission: infiniteforge.getitem
  generators:
    description: List all locations in gui
    usage: /locations
    permission: infiniteforge.locations
  infiniteforge:
    description: Main command
    usage: /infiniteforge
    permission: infiniteforge.infiniteforge
  selldrops:
    description: Sell all drops in inventory
    usage: /selldrops
    permission: infiniteforge.selldrops