name: GenX
version: '${project.version}'
main: xyz.arcadiadevs.genx.GenX
api-version: 1.19
authors:
  - Cuftica
  - OpenSource

depend:
  - Vault

commands:
  getitem:
    description: Get the generator item
    usage: /getitem
    permission: genx.getitem
  generators:
    description: List all generators in gui
    usage: /generators
    permission: genx.generators
  genx:
    description: Main command
    usage: /genx
    permission: genx.genx