name: GensPlus
version: '${project.version}'
main: xyz.arcadiadevs.gensplus.GensPlus
api-version: 1.13
authors:
  - Cuftica
  - OpenSource

depend:
  - Vault
  - ProtocolLib

softdepend:
  - Oraxen
  - Essentials
  - ItemsAdder
  - IridiumSkyblock
  - SuperiorSkyblock2
  - ASkyBlock
  - AcidIsland
  - BentoBox
  - HoloEasy

commands:
  gensplus:
    description: Main command
    usage: /gensplus
    aliases: [ gens, gp ]
  generators:
    description: List all generators in gui
    usage: /generators
  selldrops:
    description: Sell all drops in inventory
    usage: /selldrops