name: InfiniteForge
version: '${project.version}'
main: xyz.arcadiadevs.infiniteforge.InfiniteForge
api-version: 1.19
authors:
  - Cuftica
  - OpenSource

depend:
  - Vault
  - ProtocolLib

softdepend:
  - Oraxen
  - Essentials
  - ItemsAdder

commands:
  infiniteforge:
    description: Main command
    usage: /infiniteforge
    aliases: [ if, forge ]
  generators:
    description: List all generators in gui
    usage: /generators
  selldrops:
    description: Sell all drops in inventory
    usage: /selldrops