name: GensForge
version: '${project.version}'
main: xyz.arcadiadevs.gensforge.GensForge
api-version: 1.19
authors:
  - Cuftica
  - OpenSource

depend:
  - Vault
  - ProtocolLib

softdepend:
  - Oraxen
  - Essentials
  - ItemsAdder

commands:
  gensforge:
    description: Main command
    usage: /gensforge
    aliases: [ gens, gf ]
  generators:
    description: List all generators in gui
    usage: /generators
  selldrops:
    description: Sell all drops in inventory
    usage: /selldrops