name: GensPlus
version: '${project.version}'
main: xyz.arcadiadevs.gensplus.GensPlus
api-version: 1.16
authors:
  - Cuftica
  - OpenSource

depend:
  - Vault
  - ProtocolLib

softdepend:
  - Oraxen
  - Essentials
  - ItemsAdder
  - IridiumSkyblock
  - SuperiorSkyblock2
  - ASkyBlock
  - AcidIsland
  - BentoBox

commands:
  gensplus:
    description: Main command
    usage: /gensplus
    aliases: [ gp ]
  generators:
    description: List all generators in gui
    usage: /generators
    aliases: [ gens ]
  selldrops:
    description: Sell all drops in inventory
    usage: /sell